### ISSUE TITLE
Update mkdocs version requirements

### ISSUE THREAD

**Issue by vinomaster** [trustoverip/WP0010-toip-foundation-whitepaper#5]
Update line 14 in requirements.txt to [reflect changes in line 14 in the base template](https://github.com/trustoverip/mkdocs-material/blob/main/requirements.txt).

This will prevent formatting regressions.

**Comment by VictorSyntez** [comment]
This issue can be closed as requirements updated according to the template

**Comment by vinomaster** [comment]
Closed as now working.
